# Site settings
author: SB
title: The Missing Semicolon
header-img: img/home-bg.png
email: stephen@s-blais.com
copyright_name: SB
description: > # this means to ignore newlines until "baseurl:"
  - the only wrong first step is not taking a first step -
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: the_s_blais
github_username:  s-blais

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
