# Site settings
author: SB
title: Bloggy Bytes
# header-img: img/home-bg.png
header-img: img/PVD-skyline-dark.jpg
email: stephen@s-blais.com
copyright_name: SB
description: > # this means to ignore newlines until "baseurl:"
  Ramblings and musings
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: the_s_blais
github_username:  s-blais
linkedin_username: s-blais

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

# theme: jekyll-theme-minimal